### ISSUE TITLE
incorrect param name

### ISSUE THREAD

**Issue by Iced-Sun** [lizheming/drone-wechat#2]
https://github.com/lizheming/drone-wechat/blob/4c689927d843fe7fa0ab33813be20574ec2b0439/plugin.js#L49

As per [weixin doc](https://work.weixin.qq.com/api/doc#90000/90135/90236), ```tag``` should be ```totag```.

**Comment by lizheming** [comment]
ops, it's my mistake, I have fixed it. thank you for your reply~
