### ISSUE TITLE
default value of `to_user'

### ISSUE THREAD

**Issue by Iced-Sun** [lizheming/drone-wechat#3]
Currently, ```to_user``` defaults to ```@all```, in which ```to_party/to_tag``` will be totally ignored. This behavior is a bit confusing to me, since I have to always set the ```to_user``` param even I have set ```to_party/to_tag```.

Is it possible to cancel the default value of ```to_user```? That will be much appreciated.

Regards.

**Comment by lizheming** [comment]
OK, I'll change it later, thank you for your advice.
